language: ruby

rvm:
  - 2.2.9
  - 2.3.5
  - 2.4.3
  - 2.5.0

bundler_args: --binstubs

before_install:
  - gem install bundler -v 2.0.2 --no-doc

script:
  - bundle exec rake

after_success:
  - bundle exec codeclimate-test-reporter
